### ISSUE TITLE
Wrong GitHub user in config file 

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/myelin-meta-analysis#1]
Hey Agah, 

Just saw that inside the [_config.yml](https://github.com/Notebook-Factory/myelin-meta-analysis/blob/master/_config.yml), the user should be changed to **NotebookFactory**, instead of your username

![image](https://user-images.githubusercontent.com/37374247/88675155-ee782f80-d0ea-11ea-89f3-8996cd901a23.png)

**Comment by agahkarakuzu** [comment]
Thanks @zelenkastiot, solved.
