### ISSUE TITLE
[NeuroLibre review] Missing binder link icon

### ISSUE THREAD

**Issue by ltetrel** [Notebook-Factory/myelin-meta-analysis#3]
https://github.com/neurolibre/neurolibre-reviews/issues/4

On the jupyter book page, there is no "launch binder" icon. So it is not possible to access the binder instance (still possible through the binder website, but not the standard process for readers).

**Comment by agahkarakuzu** [comment]
![image](https://user-images.githubusercontent.com/9632322/138134806-d341d6bd-8496-492d-8aee-a3ff994b6404.png)

**Comment by ltetrel** [comment]
Thanks @agahkarakuzu!
This is weird, but I imagine that if it redirects you to mybinder, then there is an issue or with jupyter book, or pointing to a wrong html build.

**Comment by ltetrel** [comment]
Actually this could come from my browser that is weird, I don't see an icon on my end:
![image](https://user-images.githubusercontent.com/37963074/138136739-79e13d4d-1eae-4c74-bdb6-d6fc93645944.png)

**Comment by agahkarakuzu** [comment]
That's the introduction page, no code cells there, nothing to execute, no binder.

**Comment by agahkarakuzu** [comment]
> This is weird, but I imagine that if it redirects you to mybinder, then there is an issue or with jupyter book, or pointing to a wrong html build.

To confirm that the book build returns the latest build, I will introduce some other changes. If I don't see those changes reflected, then we have other issues.

**Comment by ltetrel** [comment]
Alright make sense!
Thank you, I will create another issue for the wrong binder link.
