### ISSUE TITLE
[NeuroLibre review] Reduce the size of the environment

### ISSUE THREAD

**Issue by ltetrel** [Notebook-Factory/myelin-meta-analysis#4]
neurolibre/neurolibre-reviews#4

The environment size is > 1GB (currently ~4GB), and should be reduced as much as possible.
Rationals for this are described in our documentation (https://docs.neurolibre.org/en/latest/SUBMIT.html#runtime).

**Comment by ltetrel** [comment]
I suggest to remove [this folder](https://github.com/Notebook-Factory/myelin-meta-analysis/tree/main/_build), as it will be built by NeuroLibre and should not live inside a github repo.
If re-execution time is an issue, consider uploading your notebook checkpoints pubilcally, downloading them using Repo2Data, and accessing them through the mounted folder `/data`.

**Comment by ltetrel** [comment]
Ok with your new build it is now at 3.98GB.

Sadly I think we will need to live with that, I imagine this is the R installation that is quite big. What do you think @agahkarakuzu ?

**Comment by agahkarakuzu** [comment]
R and Octave images tend to be like that. I don't know what layers are added in which fashion by repo2data for R, but I have no control over that. All in all my repo is `65MB`, so I think we should live with that.

**Comment by ltetrel** [comment]
> which fashion by repo2data for R

You mean repo2docker instead of repo2data I think.

Alright I will close this we need to live with that, I hope the image size will not be an issue with the user spawning.

**Comment by mathieuboudreau** [comment]
I think limiting NeuroLibre submissions to 1GB docker images in size is a huge limitation that will annoy many users during submission.

Most base notebooks hover around ~0.5gb-1.5 gb, without even the notebooks or additional dependencies.

For example, Jupyter's datascience notebook is a compressed size of 1.36GB

<img width="1276" alt="Screen Shot 2021-10-20 at 2 15 51 PM" src="https://user-images.githubusercontent.com/1421029/138141460-a464e9ed-14a8-46c0-93b1-a3fdd02f50ba.png">

If we can't handle even a basic datascience base image that users will pull, I think we need to improve our infrastructure.
