### ISSUE TITLE
[NeuroLibre review] html rendering on jupyter lab vs jupyter notebook UI

### ISSUE THREAD

**Issue by ltetrel** [Notebook-Factory/myelin-meta-analysis#6]
neurolibre/neurolibre-reviews#4

HTMLs does not render correctly on the traditionnal jupyter notebook interface, but does on jupyter lab.
Not sure if that is an issue, but by default the binder button (in the jupyter book) open a traditionnal jupyter UI on NeuroLibre (vs mybinder which open correctly a lab interface, not sure why I need to investigate that on our cluster).

**Comment by ltetrel** [comment]
![image](https://user-images.githubusercontent.com/37963074/138138692-db069de4-f557-4464-8004-f3adbc4fa01b.png)

**Comment by ltetrel** [comment]
I already saw this behaviour in previous submissions that uses jupyter lab...

**Comment by agahkarakuzu** [comment]
This issue is Plotly-specific. To render interactive figures in the `jupyter-notebook` interface, a different command is called. Maybe I can switch the default to `jupyter-lab` for BinderHub?

**Comment by ltetrel** [comment]
What do you mean by:

> Maybe I can switch the default to `jupyter-lab` for BinderHub?

Changing the binder link in the `_config` ? Or do you mean something inside the cluster itself ?

**Comment by ltetrel** [comment]
But yes definitively, if you know how to swicth to lab interface by default for this submission, it should be done. But I would not do it cluster-side (jupyter notebook interface should be the default).

**Comment by agahkarakuzu** [comment]
Actually, it is already jupyterlab. 

https://github.com/Notebook-Factory/myelin-meta-analysis/blob/030e8c58e35e4831c031f3cb8a285db02e5ce2a4/content/_config.yml#L28

**Comment by ltetrel** [comment]
~Hmm, I will try to upgrade the binderhub and see if that helps (on the public mybinder, it correctly points to a lab interface).~
Actually I was wrong, when I click on the binder icon on jupyter book, it also redirect to mybinder jupyter notebook interface.
the link is (for ex): 
https://mybinder.org/v2/gh/neurolibre/myelin-meta-analysis/main?urlpath=tree/03/meta_analysis.ipynb
When it should be 
https://mybinder.org/v2/gh/neurolibre/myelin-meta-analysis/main?urlpath=lab/tree/03/meta_analysis.ipynb

**Comment by ltetrel** [comment]
Ok I will close this since as the author mentioned this is plotly-related and using lab interface is mandatory here.
