### ISSUE TITLE
 [NeuroLibre review] External link refer to fork, not target repo

### ISSUE THREAD

**Issue by ltetrel** [Notebook-Factory/myelin-meta-analysis#7]
neurolibre/neurolibre-reviews#4

The external link section points to the neurolibre repository: https://github.com/neurolibre/myelin-meta-analysis
However at this stage, no fork exists for the user repo (review still on-going, fork is happening after).
I think we should point to target repo instead.

**Comment by ltetrel** [comment]
![image](https://user-images.githubusercontent.com/37963074/138154277-5e01e36d-a9cd-4725-b1ac-885175fd8aac.png)

**Comment by agahkarakuzu** [comment]
https://github.com/Notebook-Factory/myelin-meta-analysis/commit/27f23dc4a6c958b3d8e145b236ca819e8b20a86d
